### ISSUE TITLE
RoverwheeUndefined BaseRevolve feature (missing library file)

### ISSUE THREAD

**Issue by JimJoseStudent** [leap71/LEAP71_RoverWheel#1]
<img width="848" alt="Screenshot 2024-02-27 101429" src="https://github.com/leap71/LEAP71_RoverWheel/assets/151611137/2f1b8e2f-81f0-402f-9ab0-91b1cd77c18d">

Example is giving error when its being run, saying that BaseRevolve could not be found.

**Comment by LinKayser** [comment]
Just asking the obvious — did you include the Shape Kernel repository in your project?

Your project structure should look like this:

![image](https://github.com/leap71/LEAP71_RoverWheel/assets/148448288/33bcf440-dc29-4da4-93dd-7daed4230ee9)

Lin

**Comment by JimJoseStudent** [comment]
> Just asking the obvious — did you include the Shape Kernel repository in your project?
> 
> Your project structure should look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/148448288/308126499-33bcf440-dc29-4da4-93dd-7daed4230ee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzI0NjgsIm5iZiI6MTcwOTA3MjE2OCwicGF0aCI6Ii8xNDg0NDgyODgvMzA4MTI2NDk5LTMzYmNmNDQwLWRjMjktNGRhNC05M2RkLTdkYWVkNDIzMGVlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QyMjE2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWUwMzk0YTZiNDViYzFjYzZhYjI3ZWNlMmEzN2FkNzQ2ODUzZGJkN2ZiMzIyNmM0YjgyY2YwYWMxOTcxZDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4yGDuW8E0Ky4sJ3Kx-nxjBR6VbbVLu_FafsaAD0F_5c)
> 
> Lin

Hey, 

Thanks for the quick response. Yes, i added it similar to the HX design that was released previously. I tried looking for the BaseRevolve defition in my pickGK library files and had no luck. Im fairly new to OOP so i might be missing something. But in terms of file structure i am fairly certain i got it right, let me know if im wrong.

![image](https://github.com/leap71/LEAP71_RoverWheel/assets/151611137/b889b86f-662c-4798-a71f-3ca6cf3355e6)


Regards, 
Jim

**Comment by JimJoseStudent** [comment]
I did a search for definition across the whole PicoGK project files and there was no definition for BaseRevolve. Could this be a feature that is not part of the released library?

**Comment by josefinelissner** [comment]
Hi, Jim!

The BaseRevolve is a new BaseShape that I introduced and added to the ShapeKernel library last month. If you pull and link the latest version of ShapeKernel, it will be there ;-)

The file will then be in ShapeKernel/BaseShapes/BaseRevolve.cs
